### ISSUE TITLE
npm package?

### ISSUE THREAD

**Issue by itsmebhavin** [zavoloklom/material-design-color-palette#2]
First of all, thank you creating great collection of font & color palette. I love it. Also, Just like iconic font, would it be possible to have npm package for this color palette as well?

Thank you,

**Comment by zavoloklom** [comment]
Yes, I plan to add some features to that project (i.e. colored borders) - after that I will publish it to npm.

**Comment by itsmebhavin** [comment]
That would be awesome… can’t wait to see new features. Let me know….

**Comment by zavoloklom** [comment]
Available in NPM since [1.1.0](https://github.com/zavoloklom/material-design-color-palette/releases)

Border-color variants available since 2.0.0. 
Early access https://github.com/zavoloklom/material-design-color-palette/tree/2.0.0-dev
